"""Shared paths and expectations for the test suite.

Everything here points at samples/synthetic, which is generated by
tools/make_synthetic_samples.py and committed to the repository. The real
submissions are confidential and never leave the machine, so the suite must be
runnable by anyone who clones this.

Expected figures come from samples/synthetic/manifest.json, written by the same
script that builds the documents, so the two cannot drift apart.
"""

import json
import sys
from pathlib import Path

import pytest

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT))

SYNTHETIC = ROOT / "samples" / "synthetic"
MANIFEST_PATH = SYNTHETIC / "manifest.json"

if not MANIFEST_PATH.exists():  # pragma: no cover - a clone that has not built them
    raise RuntimeError(
        "samples/synthetic is missing. Run: python tools/make_synthetic_samples.py"
    )

MANIFEST = json.loads(MANIFEST_PATH.read_text())

POWERBI = SYNTHETIC / "powerbi-export.xlsx"
PORTAL = SYNTHETIC / "portal-export.xlsx"

# Short keys for the three documents, in a stable order.
SAMPLES = {
    "alpha": SYNTHETIC / "aldgate-fenwick_submission_2027_alpha.docx",
    "beta": SYNTHETIC / "aldgate-fenwick_submission_2027_beta.docx",
    "gamma": SYNTHETIC / "aldgate-fenwick_submission_2027_gamma.docx",
}
OLDER_VERSION = SYNTHETIC / MANIFEST["superseded"]["older"]

EXPECTED = {
    key: MANIFEST["documents"][path.name]["expected"] for key, path in SAMPLES.items()
}
DETAILS = {
    key: MANIFEST["documents"][path.name] for key, path in SAMPLES.items()
}


def expected(key, metric):
    return EXPECTED[key][metric]


@pytest.fixture(scope="session")
def manifest():
    return MANIFEST


def make_submission(path, clients=(("A Client Ltd", "Yes"),), matters=1):
    """A minimal document the parser will accept, for one-off cases."""
    from docx import Document

    document = Document()
    document.add_paragraph("Firm Name")
    document.add_table(rows=1, cols=1).rows[0].cells[0].text = "Example Firm LLP"
    document.add_paragraph("Clients: publishable clients")
    table = document.add_table(rows=len(clients) + 1, cols=2)
    table.rows[0].cells[0].text = "Active key clients (over the last 12 months)"
    table.rows[0].cells[1].text = "New client (yes/no)"
    for i, (name, answer) in enumerate(clients, start=1):
        table.rows[i].cells[0].text = name
        table.rows[i].cells[1].text = answer
    for n in range(1, matters + 1):
        matter = document.add_table(rows=2, cols=2)
        matter.rows[0].cells[0].text = f"Publishable matter {n}"
        matter.rows[1].cells[0].text = "Name of client"
        matter.rows[1].cells[1].text = f"Client {n}"
    document.save(path)
    return path
